stages:
  - code-quality
  - build
  - test
  - run

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

before_script:
  - echo "Pipeline started by $GITLAB_USER_LOGIN"
  - echo "Running on branch $CI_COMMIT_BRANCH"

check_style:
  image: maven:latest
  stage: code-quality
  script:
    - mvn checkstyle:check

show_style_report:
  image: maven:latest
  stage: code-quality
  script:
    - ./mvnw site
  artifacts:
    paths:
      - target/site/checkstyle.html

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

run:
  stage: run
  script:
    - mvn $MAVEN_CLI_OPTS package
    - mvn $MAVEN_CLI_OPTS exec:java -Dexec.mainClass="pl.pajwoj.ztp.ZtpApplication"




