stages:
  - cacheCheck
  - codeQuality
  - build
  - test

cache:
  paths:
    - .m2/repository/
    - target/
    - node_modules/

before_script:
  - echo "Pipeline started by $GITLAB_USER_LOGIN"
  - echo "Running on branch $CI_COMMIT_BRANCH"

check_cache:
  stage: cacheCheck
  image: alpine:latest
  script:
    - ls -al .m2/repository/
    - ls -al target/
    - ls -al node_modules/


backendCodeQuality:
  stage: codeQuality
  image: maven:latest
  artifacts:
    untracked: false
    when: on_success
    access: developer
    expire_in: 7 days
    paths:
      - target/site/checkstyle.html
  script:
    - mvn site

frontendCodeQuality:
  stage: codeQuality
  image: node:latest
  script:
    - npm install eslint
    - npm install eslint-plugin-react
    - npx eslint --config frontend/eslint.config.mjs .

backendBuild:
  stage: build
  image: maven:latest
  script:
    - mvn compile

frontendBuild:
  stage: build
  image: node:latest
  script:
    - cd frontend
    - npm install
    - npm run build

backendTest:
  stage: test
  image: maven:latest
  script:
    - mvn test

frontendTest:
  stage: test
  image: maven:latest
  before_script:
    - apt-get update
    - apt-get install -y nodejs npm
  script:
    - mvn spring-boot:run
    - cd frontend
    - npm install
    - npm start
    - npx cypress run
    