image: maven:latest-alpine

stages:
  - build
  - test
  - run

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

before_script:
  - echo "Pipeline started by $GITLAB_USER_LOGIN"
  - echo "Running on branch $CI_COMMIT_BRANCH"
  - chmod +x ./mvnw

build:
  stage: build
  script:
    - ./mvnw $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - ./mvnw $MAVEN_CLI_OPTS test

run:
  stage: run
  script:
    - ./mvnw $MAVEN_CLI_OPTS package
    - ./mvnw $MAVEN_CLI_OPTS exec:java -Dexec.mainClass="pl.pajwoj.ztp.ZtpApplication"




