stages:
  - build
  - test
  - run

cache:
  paths:
    - .m2/repository/
    - target/

before_script:
  - echo "Pipeline started by $GITLAB_USER_LOGIN"
  - echo "Running on branch $CI_COMMIT_BRANCH"

build:
  stage: build
  image: maven:latest
  script:
    - mvn compile

test:
  stage: test
  image: maven:latest
  script:
    - mvn test

run:
  stage: run
  image: maven:latest
  script:
    - mvn package
    - mvn exec:java -Dexec.mainClass="pl.pajwoj.ztp.ZtpApplication"




