stages:
  - code_quality
  - build
  - test

cache:
  paths:
    - .m2/repository/
    - target/

before_script:
  - echo "Pipeline started by $GITLAB_USER_LOGIN"
  - echo "Running on branch $CI_COMMIT_BRANCH"

code_quality:
  stage: code_quality
  image: maven:latest
  artifacts:
    untracked: false
    when: on_success
    access: developer
    expire_in: 7 days
    paths:
      - target/site/checkstyle.html
  script:
    - mvn site

build:
  stage: build
  image: maven:latest
  script:
    - mvn compile

test:
  stage: test
  image: maven:latest
  script:
    - mvn test