stages:
  - codeQuality
  - build
  - test
  - repository

before_script:
  - echo "Pipeline started by $GITLAB_USER_LOGIN"
  - echo "Running on branch $CI_COMMIT_BRANCH"

cache:
  key: cache-$CI_COMMIT_REF_SLUG
  paths:
    - .m2/repository/
    - frontend/node_modules/

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

backendCodeQuality:
  stage: codeQuality
  image: maven:latest
  script:
    - mvn site

  artifacts:
    untracked: false
    when: on_success
    access: developer
    expire_in: 7 days
    paths:
      - target/site/checkstyle.html

frontendCodeQuality:
  stage: codeQuality
  image: node:latest
  script:
    - cd frontend
    - npm install eslint eslint-plugin-react --save-dev
    - npx eslint --config eslint.config.mjs .

backendBuild:
  stage: build
  image: maven:latest
  script:
    - mvn compile

  dependencies:
    - backendCodeQuality

frontendBuild:
  stage: build
  image: node:latest
  script:
    - cd frontend
    - npm install
    - npm run build

  dependencies:
    - frontendCodeQuality

backendTest:
  stage: test
  image: maven:latest
  script:
    - mvn test

  dependencies:
    - backendCodeQuality
    - backendBuild

frontendTest:
  stage: test
  image: node:latest

  before_script:
    - apt-get update
    - apt-get install -y openjdk-17-jdk maven libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb #maven, java and all cypress deps
  script:
    - mvn spring-boot:run > /dev/null 2>&1 &
    - cd frontend
    - npm install
    - npm start > /dev/null 2>&1 &
    - sleep 30 #just to be sure I guess
    - npm install cypress --save-dev
    - npx cypress install
    - npx cypress run

  dependencies:
    - frontendCodeQuality
    - frontendBuild
    - backendCodeQuality
    - backendBuild

pushToRepository:
  stage: repository
  image: alpine:latest

  services: 
    - docker:dind

  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t pajwoj/ztp-libraryapp:$CI_COMMIT_SHORT_SHA .
    - docker push pajwoj/ztp-libraryapp:$CI_COMMIT_SHORT_SHA