stages:
  - backendCodeQuality
  - frontendCodeQuality
  - backendBuild
  - backendTest
  - frontendTest

cache:
  paths:
    - .m2/repository/
    - target/
    - node_modules/

before_script:
  - echo "Pipeline started by $GITLAB_USER_LOGIN"
  - echo "Running on branch $CI_COMMIT_BRANCH"

backendCodeQuality:
  stage: backendCodeQuality
  image: maven:latest
  artifacts:
    untracked: false
    when: on_success
    access: developer
    expire_in: 7 days
    paths:
      - target/site/checkstyle.html
  script:
    - mvn site

frontendCodeQuality:
  stage: frontendCodeQuality
  image: node:latest
  script:
    - npm install eslint
    - npm install eslint-plugin-react
    - npx eslint --config frontend/eslint.config.mjs .

backendBuild:
  stage: backendBuild
  image: maven:latest
  script:
    - mvn compile

backendTest:
  stage: backendTest
  image: maven:latest
  script:
    - mvn test

frontendTest:
  stage: frontendTest
  image: maven:latest
  before_script:
    - apt-get update
    - apt-get install -y nodejs npm
  script:
    - mvn spring-boot:run
    - cd frontend
    - npm install
    - npm start
    - npx cypress run
    