stages:
  - code_quality
  - build
  - test

before_script:
  - echo "Pipeline started by $GITLAB_USER_LOGIN"
  - echo "Running on branch $CI_COMMIT_BRANCH"

code_quality:
  stage: code_quality
  image: maven:latest
  cache:
    paths:
      - target/
  script:
    - mvn site

build:
  stage: build
  image: maven:latest
  script:
    - mvn compile

test:
  stage: test
  image: maven:latest
  script:
    - mvn test




